title: SciAgent
description: Documentation for SciAgent
theme: minima

# Important for https://sciagent-ai.github.io/sciagent/
url: "https://sciagent-ai.github.io"
baseurl: "/sciagent"

# Navigation (see next section)
minima:
  nav_pages:
    - index.md




